server:
  port: 8080
  error:    path: /error
  servlet:    session:      timeout: 30m
  tomcat:    basedir: ./logs
    max-threads: 500
    uri-encoding: utf-8
spring:
  datasource:    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.10.138:3306/chapter05?characherEncodeing=utf8&&serverTimezone=Asia/Shanghai
    username: tester
    password: 84519741
  devtools:    restart:      enabled: true
      exclude: WEB-IINF/**
  servlet:    multipart:      enabled: true
      file-size-threshold: 0
      max-file-size: 1MB
      max-request-size: 10MB
      resolve-lazily: false  http:    encoding:      force: true
      charset: utf-8
      enabled: true
