server:
  port: 8080
  error:    path: /error
  servlet:    session:      timeout: 30m
  tomcat:    basedir: ./logs
    max-threads: 500
    uri-encoding: utf-8
spring:
  servlet:    multipart:      enabled: true
      file-size-threshold: 0
      max-file-size: 1MB
      max-request-size: 10MB
      resolve-lazily: false  http:    encoding:      force: true
      charset: utf-8
      enabled: true
config:
  name: 三国演义
  author: 罗贯中
  price: 20